# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95bbdb57efa943ca8e507c838026528614d04552974deb6d24d1658dfa5549d57cf115dd4adbb671fb2d9904b200bcf093c56314fb9fc3bded1ebca833d2d26e

test:
  secret_key_base: ce72f9f92b3f0e376112f6dcb315697e1f36645d26efd3db897273d7885c7f42febcaa294f3b4dcafaba9827fbfd7aacc35c7bf9a753d6db545a0e5d483d5246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
